#pragma once

class FMonitoredProcess;

/**
 * Structure representing the result of a CLI command with helper functions to parse the output
 */
struct FCliResult
{
	/**
	 * Output generated by the command
	 */
	FString Output;
	/**
	 * Error encountered while running the command, if any
	 */
	TOptional<FString> Error;
	/**
	 * Helper function to determine if the command was successfully run
	 * Note: This does not mean the command itself was successful, only that the process completed successfully
	 */
	bool DidSucceed() const;
	/**
	 * Helper function to retrieve the parsed output as a JSON object
	 */
	TSharedPtr<FJsonObject> OutputAsJsonObject() const;
	/**
	 * Helper function to retrieve the parsed output as an array of JSON objects
	 */
	TArray<TSharedPtr<FJsonValue>> OutputAsJsonArray() const;
};

/**
 * Structure representing all the configurable parameters for running a CLI command
 */
struct FCliParameters
{
	FCliParameters(const FString& InCommand);

	/**
	 * The AP CLI command we should run with all the necessary parameters
	 */
	FString Command;
	/**
	 * If true, the command will be run using the `-config` flag using an .ini file
	 */
	bool bUseIniFile;
	/**
	 * If true, the command will be run using the `-json` flag
	 */
	bool bRequestJsonOutput;
	/**
	 * Callback executed to determine if we should terminate the process early.
	 * If the caller wants to terminate early, they should return true
	 */
	using FOnProcessUpdate = TFunction<bool(const TSharedPtr<FMonitoredProcess>& InProcess, const FString& ProcessOutput)>;
	FOnProcessUpdate OnProcessUpdate;
};

namespace AnchorpointCliUtils
{
	FString ConvertCommandToIni(const FString& InCommand, bool bPrintConfig = false, bool bJsonOutput = true);

	FCliResult RunApCommand(const FCliParameters& InParameters);
	FCliResult RunGitCommand(const FString& InCommand);
}