name: Plugin Release

on:
  push:
    tags:
      - 'v*'

jobs:
  plugin-cd:
    uses:  outoftheboxplugins/BuildMachines/.github/workflows/release-to-github.yml@master
    with:
      plugin_name: "Anchorpoint"
      exclude_patterns: "-x \".github/*\" -x \".git/*\" -x \".gitignore\" -x \".gitattributes\""

    secrets: inherit
