name: Plugin Release

on:
  push:
    tags:
      - 'v*'

jobs:
  plugin-cd:
    uses:  outoftheboxplugins/BuildMachines/.github/workflows/release-to-github.yml@master
    with:
      plugin_name: "Anchorpoint"
    secrets: inherit
